hplc:
  timeout: 10000 #s
  baud rate: 9600 #s^-1
  data bits: 8 
  parity: None 
  stop bits: 1
  flow control: None
  format: "RU{0:3d}" #ascii 
legato: 
  timeout: 10000
  baud rate: 9600 #s^-1
  data bits: 8
  parity: None
  stop bits: 1
  flow control: None
  format: "irate;{0:4.4f} {1} \r\n" #ascii
alicat:
  timeout: 500 #s
  termination character: "\r"
  flow control: None
  end mode for reads: termination character
  end mode for writes: termination character
  baud rate: 19200 #s^-1
  format: see prots directory or alicat package
